# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "Description of what the lane does"
  lane :generate_ipa_develop do 
get_certificates(
	keychain_path:"/Users/sagarpanwala/Library/Keychains/login.keychain-db",
	keychain_password:"1234"
)
get_provisioning_profile(
  adhoc: true,
  force: true,
  filename: "71abf8e4-d402-44b6-8591-04a1ccc1b803.mobileprovision"
)
  build_app
   gym(
      configuration: "Release",
      scheme: "Test",
      clean: true,
      export_method: 'development',
      output_name: "JenkinsFastLaneTestApp.iOS.ipa",
archive: true)
  end
end
